"""Intent stack: contracts, routing, and parsing."""

from .schema import (
    AgentSession,
    Context,
    DisambiguationOption,
    DisambiguationPrompt,
    FocusInfo,
    Intent,
    OverlayOp,
    PendingAction,
    ProjectProfile,
    RepoInfo,
    Result,
    RiskClass,
    ScreenFrame,
    SlotSpec,
    Status,
    Support,
    UndoToken,
    Verb,
)

__all__ = [
    "AgentSession",
    "Context",
    "DisambiguationOption",
    "DisambiguationPrompt",
    "FocusInfo",
    "Intent",
    "OverlayOp",
    "PendingAction",
    "ProjectProfile",
    "RepoInfo",
    "Result",
    "RiskClass",
    "ScreenFrame",
    "SlotSpec",
    "Status",
    "Support",
    "UndoToken",
    "Verb",
]
